# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resize.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='resize.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0cresize.proto\"-\n\x0cMyResizeArgs\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x62\x06proto3')
)




_MYRESIZEARGS = _descriptor.Descriptor(
  name='MyResizeArgs',
  full_name='MyResizeArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='MyResizeArgs.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='MyResizeArgs.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=61,
)

DESCRIPTOR.message_types_by_name['MyResizeArgs'] = _MYRESIZEARGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MyResizeArgs = _reflection.GeneratedProtocolMessageType('MyResizeArgs', (_message.Message,), dict(
  DESCRIPTOR = _MYRESIZEARGS,
  __module__ = 'resize_pb2'
  # @@protoc_insertion_point(class_scope:MyResizeArgs)
  ))
_sym_db.RegisterMessage(MyResizeArgs)


# @@protoc_insertion_point(module_scope)
