version: "2.3"
services:
  gpu:
    image: scannerresearch/scannertools:gpu-9.1-cudnn7-latest
    command: bash -c "cd /opt/scanner && jupyter notebook --allow-root --ip=0.0.0.0 --port=8888"
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    runtime: nvidia
  cpu:
    image: scannerresearch/scannertools:cpu-latest
    command: bash -c "cd /opt/scanner && jupyter notebook --allow-root --ip=0.0.0.0 --port=8888"
    ports:
      - "8888:8888"
    volumes:
      - .:/app
